### ISSUE TITLE
WHAT HAPPENED TO THE USER POPOUTS

### ISSUE THREAD

**Issue by Potaaaaato** [Pavui/Nebula#1]
OH NO
![image](https://user-images.githubusercontent.com/40638909/110517909-51d63100-80c0-11eb-8cd6-a641c46a1b1d.png)

**Comment by Potaaaaato** [comment]
UPDATE: This only happens in GCs it looks fine in servers

**Comment by Potaaaaato** [comment]
UPDATE: There have been like 50 updates but the issue still remains.

**Comment by Pavui** [comment]
Are you using BD or Powercord?
