### ISSUE TITLE
Pavy

### ISSUE THREAD

**Issue by MiyFr** [Pavui/Nebula#1]
Be looking so cute ( dk what to do )

**Comment by MiyFr** [comment]
idk, but tbh i think it's something about the theme that makes Pavy (Pavy#6125) look extra cute. idk if it's a bug or a feature but i just- 👉👈

To reproduce: Dm Pavy#6125, send a message, behold.

**Comment by Pavui** [comment]
Hm.. I don't remember putting that in the code... Can you send a screenshot of the bug?

**Comment by MiyFr** [comment]
Well, it's pretty easy to reproduce the bug so here's a screenshot below of it occurring. ![unknown](https://user-images.githubusercontent.com/72703954/112164409-3d1b9200-8bc4-11eb-98c0-6153e173c216.png)

**Comment by Pavui** [comment]
Ah! That right there... Hmm... Try switching to dark mode in your windows settings.

**Comment by MiyFr** [comment]
D-dark mode? what's that...

**Comment by Pavui** [comment]
Dark mode, in the personalization category of the settings.

**Comment by MiyFr** [comment]
I seem to have eye strains trying and adapting to dark mode... is this normal? and how could i fix it... i'll have to switch back to light mode in the meantime. i'll switch Nebula to light mode as well to better support my eye's health.

**Comment by Pavui** [comment]
You should be trialed as an adult with mass homicide charges for switching to light mode.

**Comment by MiyFr** [comment]
_*turns your light mode on as well*_

**Comment by poob1** [comment]
wtf did i read
