### ISSUE TITLE
Some issues when Discord window is maximised

### ISSUE THREAD

**Issue by romhacks** [Pavui/Nebula#2]
It seems that there are a few graphical issues that only appear when the window is maximised, and not when it is free floating.

First, when the window is maximised, the user info popout seems to cut off the section with the user's icon.
![image](https://user-images.githubusercontent.com/42524580/112332610-41ad7c80-8c90-11eb-8ae4-ef23cce24a07.png)
When it is not maximised, this appears normally. 
![image](https://user-images.githubusercontent.com/42524580/112332693-568a1000-8c90-11eb-80ef-44a2b49e6e37.png)

Second, there is an odd box that appears when the settings pane is open.
![image](https://user-images.githubusercontent.com/42524580/112332927-8507eb00-8c90-11eb-9950-aa771c5f6ef2.png)
Again, this appears normally when the window is not maximised.
![image](https://user-images.githubusercontent.com/42524580/112333021-9cdf6f00-8c90-11eb-83a5-df97fe16d032.png)

I'm using Powercord, if there's any more details I can provide, I'd be happy to do so.

**Comment by Pavui** [comment]
All these issues have been fixed please git pull or reinstall, thank you.
