### ISSUE TITLE
Theme completely broke on Powercord

### ISSUE THREAD

**Issue by Potaaaaato** [Pavui/Nebula#3]
I just recently updated with git pull and this happened: 
![image](https://user-images.githubusercontent.com/40638909/111034257-97993f00-83c9-11eb-876e-8f9024024761.png)
Completely normal discord and power cord Is still active as I can see the "Powercord" settings.

**Comment by Pavui** [comment]
reinstall the theme

**Comment by Potaaaaato** [comment]
I did and it still doesnt work

**Comment by Potaaaaato** [comment]
It happened after your update

**Comment by Pavui** [comment]
Alright hold on ill see what I can do.

**Comment by Pavui** [comment]
You can git pull now, fixed it.
