### ISSUE TITLE
Scrolling sometimes jumps

### ISSUE THREAD

**Issue by ConradValois** [Pavui/Nebula#4]
Title, when I scroll in discord channels it often jumps/stops eventhough I continue scrolling (as seen in the video). If I turn off nebula, the jumping stops. 

System details: 
Stable 80728 (81b6702) _(Icon was manually changed to the canary one)_
BBD 0.3.5
Host 0.0.309
Injector 0.6.2 _(No other injected services, no powercord etc)_
Windows 10 64-Bit (10.0.19042)
Nebula 3 Beta Release

https://user-images.githubusercontent.com/28946264/112807396-253a8700-9078-11eb-839b-3c7e7be2b46f.mp4

**Comment by Pavui** [comment]
I believe this is an issue with discord itself, when I disable the theme it still happens. Smooth scrolling plugin may be causing it as well.
