### ISSUE TITLE
Suggestion on muted channels

### ISSUE THREAD

**Issue by Itskeko14** [Pavui/Nebula#5]
Hi
I have seen that in Nebula 3 version 3.7.6 Beta Release there is almost no difference between muted channels and channels with unread messages, and it can be confusing if you don't look twice.
Screenshot: https://i.imgur.com/zPdCbDW.png
*The first channel is muted and the second channel has an unread message.*
Instead, I suggest that muted channels change colour to a darker colour, as in the default version of discord.

Thank you!

**Comment by Pavui** [comment]
Thanks for the suggetion, ill consider it.
